In [1]:
#Perform the following operations using Python on the Air quality and Heart Diseases data sets
#a. Data cleaning
#b. Data integration
#c. Data transformation
#d. Error correcting
#e. Data model building

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [4]:
# Display settings for structured output
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 3000)

In [6]:
# =========================================================
# LOAD DATASET
# =========================================================

# Load Air Quality Dataset
df = pd.read_csv("AirQuality.csv", sep=';')

# Display Dataset
display(df.head())

         Date      Time CO(GT)  PT08.S1(CO)  NMHC(GT) C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)     T    RH      AH  Unnamed: 15  Unnamed: 16
0  10/03/2004  18.00.00    2,6       1360.0     150.0     11,9         1046.0    166.0        1056.0    113.0        1692.0       1268.0  13,6  48,9  0,7578          NaN          NaN
1  10/03/2004  19.00.00      2       1292.0     112.0      9,4          955.0    103.0        1174.0     92.0        1559.0        972.0  13,3  47,7  0,7255          NaN          NaN
2  10/03/2004  20.00.00    2,2       1402.0      88.0      9,0          939.0    131.0        1140.0    114.0        1555.0       1074.0  11,9  54,0  0,7502          NaN          NaN
3  10/03/2004  21.00.00    2,2       1376.0      80.0      9,2          948.0    172.0        1092.0    122.0        1584.0       1203.0  11,0  60,0  0,7867          NaN          NaN
4  10/03/2004  22.00.00    1,6       1272.0      51.0      6,5          836.0    131.0        1205.0    116.0        1490.0       1110.0  11,2  59,6  0,7888          NaN          NaN

In [7]:
# =========================================================
# a. DATA CLEANING
# =========================================================

# Remove Unwanted Columns
df.drop(columns=['Unnamed: 15', 'Unnamed: 16'], inplace=True)

# Display Dataset
display(df.head())

         Date      Time CO(GT)  PT08.S1(CO)  NMHC(GT) C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)     T    RH      AH
0  10/03/2004  18.00.00    2,6       1360.0     150.0     11,9         1046.0    166.0        1056.0    113.0        1692.0       1268.0  13,6  48,9  0,7578
1  10/03/2004  19.00.00      2       1292.0     112.0      9,4          955.0    103.0        1174.0     92.0        1559.0        972.0  13,3  47,7  0,7255
2  10/03/2004  20.00.00    2,2       1402.0      88.0      9,0          939.0    131.0        1140.0    114.0        1555.0       1074.0  11,9  54,0  0,7502
3  10/03/2004  21.00.00    2,2       1376.0      80.0      9,2          948.0    172.0        1092.0    122.0        1584.0       1203.0  11,0  60,0  0,7867
4  10/03/2004  22.00.00    1,6       1272.0      51.0      6,5          836.0    131.0        1205.0    116.0        1490.0       1110.0  11,2  59,6  0,7888

In [25]:
# Remove null values
df.dropna(inplace=True)

In [9]:
# ---------------------------------------------------------
# Remove Duplicate Values
# ---------------------------------------------------------

df.drop_duplicates(inplace=True)

# Display Shape After Removing Duplicates
print("Shape After drop_duplicates():", df.shape)

Shape After drop_duplicates(): (9357, 15)

In [28]:
# Convert datatype
cols = ['CO(GT)','C6H6(GT)','T','RH','AH']

for col in cols:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace(',', '.')
    df[col] = df[col].astype(float)

# Display cleaned data
display(df.head())

         Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)     T    RH      AH  Scaled_CO     Log_T  Temp_Humidity
0  10/03/2004  18.00.00     2.6       1360.0     150.0      11.9         1046.0    166.0        1056.0    113.0        1692.0       1268.0  13.6  48.9  0.7578      260.0  2.610070         665.04
1  10/03/2004  19.00.00     2.0       1292.0     112.0       9.4          955.0    103.0        1174.0     92.0        1559.0        972.0  13.3  47.7  0.7255      200.0  2.587764         634.41
2  10/03/2004  20.00.00     2.2       1402.0      88.0       9.0          939.0    131.0        1140.0    114.0        1555.0       1074.0  11.9  54.0  0.7502      220.0  2.476538         642.60
3  10/03/2004  21.00.00     2.2       1376.0      80.0       9.2          948.0    172.0        1092.0    122.0        1584.0       1203.0  11.0  60.0  0.7867      220.0  2.397895         660.00
4  10/03/2004  22.00.00     1.6       1272.0      51.0       6.5          836.0    131.0        1205.0    116.0        1490.0       1110.0  11.2  59.6  0.7888      160.0  2.415914         667.52

In [29]:
# ==================================================
# b. DATA INTEGRATION
# ==================================================

# Create subsets
df1 = df.iloc[0:50]
df2 = df.iloc[50:100]

# Merge data
merged_df = pd.concat([df1, df2])

# Display merged data
display(merged_df.head())

         Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)     T    RH      AH  Scaled_CO     Log_T  Temp_Humidity
0  10/03/2004  18.00.00     2.6       1360.0     150.0      11.9         1046.0    166.0        1056.0    113.0        1692.0       1268.0  13.6  48.9  0.7578      260.0  2.610070         665.04
1  10/03/2004  19.00.00     2.0       1292.0     112.0       9.4          955.0    103.0        1174.0     92.0        1559.0        972.0  13.3  47.7  0.7255      200.0  2.587764         634.41
2  10/03/2004  20.00.00     2.2       1402.0      88.0       9.0          939.0    131.0        1140.0    114.0        1555.0       1074.0  11.9  54.0  0.7502      220.0  2.476538         642.60
3  10/03/2004  21.00.00     2.2       1376.0      80.0       9.2          948.0    172.0        1092.0    122.0        1584.0       1203.0  11.0  60.0  0.7867      220.0  2.397895         660.00
4  10/03/2004  22.00.00     1.6       1272.0      51.0       6.5          836.0    131.0        1205.0    116.0        1490.0       1110.0  11.2  59.6  0.7888      160.0  2.415914         667.52

In [30]:
# ==================================================
# c. DATA TRANSFORMATION
# ==================================================

# Scaling
df['Scaled_CO'] = df['CO(GT)'] * 100

# Log transformation
df['Log_T'] = np.log(df['T'])

# Display transformed data
display(df[['CO(GT)','Scaled_CO','T','Log_T']].head())

C:\Users\Pritesh\anaconda3\envs\datamind\lib\site-packages\pandas\core\arraylike.py:396: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

   CO(GT)  Scaled_CO     T     Log_T
0     2.6      260.0  13.6  2.610070
1     2.0      200.0  13.3  2.587764
2     2.2      220.0  11.9  2.476538
3     2.2      220.0  11.0  2.397895
4     1.6      160.0  11.2  2.415914

In [31]:
# ==================================================
# d. ERROR CORRECTION
# ==================================================

# Replace invalid values
df['CO(GT)'] = df['CO(GT)'].replace(-200, np.nan)

# Remove outliers using IQR
Q1 = df['T'].quantile(0.25)
Q3 = df['T'].quantile(0.75)

IQR = Q3 - Q1

df = df[(df['T'] >= Q1 - 1.5*IQR) & (df['T'] <= Q3 + 1.5*IQR)]

# Display corrected data
display(df.head())

         Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)     T    RH      AH  Scaled_CO     Log_T  Temp_Humidity
0  10/03/2004  18.00.00     2.6       1360.0     150.0      11.9         1046.0    166.0        1056.0    113.0        1692.0       1268.0  13.6  48.9  0.7578      260.0  2.610070         665.04
1  10/03/2004  19.00.00     2.0       1292.0     112.0       9.4          955.0    103.0        1174.0     92.0        1559.0        972.0  13.3  47.7  0.7255      200.0  2.587764         634.41
2  10/03/2004  20.00.00     2.2       1402.0      88.0       9.0          939.0    131.0        1140.0    114.0        1555.0       1074.0  11.9  54.0  0.7502      220.0  2.476538         642.60
3  10/03/2004  21.00.00     2.2       1376.0      80.0       9.2          948.0    172.0        1092.0    122.0        1584.0       1203.0  11.0  60.0  0.7867      220.0  2.397895         660.00
4  10/03/2004  22.00.00     1.6       1272.0      51.0       6.5          836.0    131.0        1205.0    116.0        1490.0       1110.0  11.2  59.6  0.7888      160.0  2.415914         667.52

In [32]:
# ==================================================
# e. DATA MODEL BUILDING
# ==================================================

# Features and target
X = df[['CO(GT)','T','RH']]

y = df['AH']

In [37]:
# Remove null values
combined = pd.concat([X,y], axis=1)

combined.dropna(inplace=True)

X = combined[['CO(GT)','T','RH']]

y = combined['AH']

# Display X
display(X.head())

# Display y
display(y.head())

   CO(GT)     T    RH
0     2.6  13.6  48.9
1     2.0  13.3  47.7
2     2.2  11.9  54.0
3     2.2  11.0  60.0
4     1.6  11.2  59.6

0    0.7578
1    0.7255
2    0.7502
3    0.7867
4    0.7888
Name: AH, dtype: float64

In [35]:
# Split data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [18]:
# =========================================================
# e. DATA MODEL BUILDING
# =========================================================

# Select Features and Target
X = df[['CO(GT)', 'T', 'RH']]

y = df['AH']

In [38]:
# ---------------------------------------------------------
# Split Dataset
# ---------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Display Shapes
print("X_train Shape :", X_train.shape)
print("X_test Shape  :", X_test.shape)
print("y_train Shape :", y_train.shape)
print("y_test Shape  :", y_test.shape)

X_train Shape : (5860, 3)
X_test Shape  : (1466, 3)
y_train Shape : (5860,)
y_test Shape  : (1466,)

In [41]:
# Train model
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Display predictions
display(pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
}).head())

   Actual  Predicted
0  0.6942   0.776528
1  1.4262   1.298893
2  0.9096   1.122638
3  1.1506   1.249190
4  1.7048   1.459177

In [43]:
# Display Training Data
display(X_train.head())

# Display Testing Data
display(X_test.head())

      CO(GT)     T    RH
3486     0.1  26.4  52.2
735      2.0  15.0  53.1
5151     4.6  19.7  68.9
4693     4.1  18.5  68.9
827      0.9  10.2  65.8

      CO(GT)     T    RH
8348     1.8   8.1  64.0
1988     1.6  25.7  43.8
6373     1.4   8.7  80.8
6290     5.3  13.3  75.8
3773     0.9  26.7  49.5

In [44]:
# =========================================================
# COMPLETE VIVA NOTES - ASSIGNMENT 2
# AIR QUALITY + HEART DISEASE DATASET
# =========================================================


# =========================================================
# 1. WHAT IS THIS PRACTICAL?
# =========================================================

# This practical performs:
# a. Data Cleaning
# b. Data Integration
# c. Data Transformation
# d. Error Correction
# e. Data Model Building


# =========================================================
# 2. WHY IMPORT pandas AS pd?
# =========================================================

# Pandas is used for:
# - Data analysis
# - DataFrame operations
# - Data manipulation


# =========================================================
# 3. WHY IMPORT numpy AS np?
# =========================================================

# NumPy is used for:
# - Numerical operations
# - Arrays
# - Mathematical functions


# =========================================================
# 4. WHY sep=';' IS USED?
# =========================================================

# AirQuality dataset uses semicolon separator (;)

# Example:
# df = pd.read_csv("AirQuality.csv", sep=';')


# =========================================================
# 5. WHAT IS A DATAFRAME?
# =========================================================

# A DataFrame is a 2D tabular structure
# containing rows and columns.


# =========================================================
# 6. WHY USE display()?
# =========================================================

# display() shows structured table output.

# print(df) gives ugly wrapped output.

# display(df.head()) gives clean table format.


# =========================================================
# 7. WHAT IS DATA CLEANING?
# =========================================================

# Process of removing:
# - null values
# - duplicates
# - unwanted columns
# - incorrect datatypes


# =========================================================
# 8. WHY REMOVE UNWANTED COLUMNS?
# =========================================================

# Columns like:
# 'Unnamed: 15'
# 'Unnamed: 16'

# contain unnecessary empty values.


# =========================================================
# 9. WHAT DOES dropna() DO?
# =========================================================

# Removes rows containing null values.

# Example:
# df.dropna(inplace=True)


# =========================================================
# 10. WHAT DOES drop_duplicates() DO?
# =========================================================

# Removes duplicate rows.

# Example:
# df.drop_duplicates(inplace=True)


# =========================================================
# 11. WHY CONVERT DATATYPE?
# =========================================================

# Machine learning models require numeric values.

# Example:
# df[col] = df[col].astype(float)


# =========================================================
# 12. WHY REPLACE ',' WITH '.' ?
# =========================================================

# Dataset contains decimal values like:
# 2,6

# Python expects:
# 2.6

# So:
# .str.replace(',', '.')


# =========================================================
# 13. WHY AttributeError OCCURS?
# =========================================================

# Because .str only works on string datatype.

# Fix:
# df[col] = df[col].astype(str)


# =========================================================
# 14. WHAT IS DATA INTEGRATION?
# =========================================================

# Combining multiple datasets/subsets together.


# =========================================================
# 15. WHAT DOES pd.concat() DO?
# =========================================================

# Concatenates multiple DataFrames.

# Example:
# merged_df = pd.concat([df1, df2])


# =========================================================
# 16. WHAT IS DATA TRANSFORMATION?
# =========================================================

# Modifying or scaling data values.


# =========================================================
# 17. WHAT IS SCALING?
# =========================================================

# Multiplying/dividing values to change range.

# Example:
# df['Scaled_CO'] = df['CO(GT)'] * 100


# =========================================================
# 18. WHAT IS LOG TRANSFORMATION?
# =========================================================

# Converts skewed data into normalized form.

# Example:
# np.log(df['T'])


# =========================================================
# 19. WHAT IS FEATURE CREATION?
# =========================================================

# Creating new column from existing columns.

# Example:
# df['Temp_Humidity'] = df['T'] * df['RH']


# =========================================================
# 20. WHAT IS ERROR CORRECTION?
# =========================================================

# Fixing:
# - invalid values
# - outliers
# - inconsistent data


# =========================================================
# 21. WHY REPLACE -200 VALUES?
# =========================================================

# In AirQuality dataset:
# -200 represents missing/invalid values.

# Example:
# df['CO(GT)'] = df['CO(GT)'].replace(-200, np.nan)


# =========================================================
# 22. WHAT IS AN OUTLIER?
# =========================================================

# Extreme value far away from normal values.


# =========================================================
# 23. WHAT IS IQR METHOD?
# =========================================================

# IQR = Q3 - Q1

# Used to detect outliers statistically.


# =========================================================
# 24. OUTLIER FORMULA
# =========================================================

# Lower Limit:
# Q1 - 1.5 * IQR

# Upper Limit:
# Q3 + 1.5 * IQR


# =========================================================
# 25. WHAT IS DATA MODEL BUILDING?
# =========================================================

# Training machine learning model using dataset.


# =========================================================
# 26. WHY USE LinearRegression?
# =========================================================

# Used for predicting continuous numerical values.


# =========================================================
# 27. WHAT IS X?
# =========================================================

# X = Features/Input variables

# Example:
# X = df[['CO(GT)','T','RH']]


# =========================================================
# 28. WHAT IS y?
# =========================================================

# y = Target/Output variable

# Example:
# y = df['AH']


# =========================================================
# 29. WHAT IS train_test_split()?
# =========================================================

# Splits dataset into:
# - training data
# - testing data


# =========================================================
# 30. WHY test_size=0.2 ?
# =========================================================

# 80% data used for training
# 20% data used for testing


# =========================================================
# 31. WHAT IS random_state?
# =========================================================

# Used for reproducible output.


# =========================================================
# 32. WHAT DOES model.fit() DO?
# =========================================================

# Trains machine learning model.

# Example:
# model.fit(X_train, y_train)


# =========================================================
# 33. WHAT DOES model.predict() DO?
# =========================================================

# Predicts output values using trained model.


# =========================================================
# 34. WHY CREATE Actual vs Predicted TABLE?
# =========================================================

# To compare:
# - actual values
# - predicted values


# =========================================================
# 35. COMMON ERRORS
# =========================================================

# FileNotFoundError
# Dataset not in same folder.

# KeyError
# Wrong column name.

# AttributeError
# Using .str on float datatype.

# ValueError
# NaN values in model training.


# =========================================================
# 36. IF EXTERNAL ASKS:
# "CHANGE TARGET VARIABLE"
# =========================================================

# y = df['T']

# or

# y = df['RH']


# =========================================================
# 37. IF EXTERNAL ASKS:
# "ADD MORE FEATURES"
# =========================================================

# X = df[['CO(GT)','T','RH','NO2(GT)']]


# =========================================================
# 38. IF EXTERNAL ASKS:
# "CHANGE TEST SIZE"
# =========================================================

# test_size = 0.3


# =========================================================
# 39. IF EXTERNAL ASKS:
# "USE DIFFERENT MODEL"
# =========================================================

# from sklearn.tree import DecisionTreeRegressor

# model = DecisionTreeRegressor()


# =========================================================
# 40. IF EXTERNAL ASKS:
# "DISPLAY FIRST 10 ROWS"
# =========================================================

# display(df.head(10))


# =========================================================
# 41. IF EXTERNAL ASKS:
# "DISPLAY LAST ROWS"
# =========================================================

# display(df.tail())


# =========================================================
# 42. IF EXTERNAL ASKS:
# "DISPLAY SHAPE"
# =========================================================

# print(df.shape)


# =========================================================
# 43. IF EXTERNAL ASKS:
# "DISPLAY DATATYPES"
# =========================================================

# print(df.dtypes)


# =========================================================
# 44. IF EXTERNAL ASKS:
# "DISPLAY COLUMN NAMES"
# =========================================================

# print(df.columns)


# =========================================================
# 45. IF EXTERNAL ASKS:
# "DISPLAY NULL VALUES"
# =========================================================

# print(df.isnull().sum())


# =========================================================
# 46. IF EXTERNAL ASKS:
# "REMOVE DUPLICATES"
# =========================================================

# df.drop_duplicates(inplace=True)


# =========================================================
# 47. IF EXTERNAL ASKS:
# "SAVE NEW DATASET"
# =========================================================

# df.to_csv("new_dataset.csv", index=False)


# =========================================================
# 48. IF EXTERNAL ASKS:
# "SHOW MODEL ACCURACY"
# =========================================================

# print(model.score(X_test, y_test))


# =========================================================
# 49. MOST IMPORTANT THEORY QUESTIONS
# =========================================================

# What is Machine Learning?
# Training computer to learn from data.

# What is Regression?
# Predicting continuous values.

# What is Dataset?
# Collection of related data.

# What is Feature?
# Input variable.

# What is Target Variable?
# Output variable.

# What is Prediction?
# Estimated output generated by model.


# =========================================================
# 50. MOST IMPORTANT COMMANDS
# =========================================================

# df.head()
# First 5 rows

# df.tail()
# Last 5 rows

# df.info()
# Dataset information

# df.describe()
# Statistical summary

# df.columns
# Column names

# df.shape
# Dataset shape

# df.dtypes
# Datatypes


# =========================================================
# END OF COMPLETE VIVA NOTES
# =========================================================