In [55]:
#1. Perform the following operations using Python on the Facebook metrics data sets
#a. Create data subsets
#b. Merge Data
#c. Sort Data
#d. Transposing Data
#e. Shape and reshape Data

In [56]:
import pandas as pd
import numpy as np

In [57]:
df = pd.read_csv("dataset_Facebook.csv", sep=';')

In [58]:
# Display settings for proper structured output
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 3000)

In [59]:
# 1. Display Dataset
display(df.head())

   Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  Lifetime Engaged Users  Lifetime Post Consumers  Lifetime Post Consumptions  Lifetime Post Impressions by people who have liked your Page  Lifetime Post reach by people who like your Page  Lifetime People who have liked your Page and engaged with your post  comment    like  share  Total Interactions
0            139441   Photo         2          12             4          3   0.0                       2752                             5091                     178                      109                         159                                               3078                                                         1640                                                119                          4    79.0   17.0                 100
1            139441  Status         2          12             3         10   0.0                      10460                            19057                    1457                     1361                        1674                                              11710                                                         6112                                               1108                          5   130.0   29.0                 164
2            139441   Photo         3          12             3          3   0.0                       2413                             4373                     177                      113                         154                                               2812                                                         1503                                                132                          0    66.0   14.0                  80
3            139441   Photo         2          12             2         10   1.0                      50128                            87991                    2211                      790                        1119                                              61027                                                        32048                                               1386                         58  1572.0  147.0                1777
4            139441   Photo         2          12             2          3   0.0                       7244                            13594                     671                      410                         580                                               6228                                                         3200                                                396                         19   325.0   49.0                 393

In [60]:
# =========================================================
# a. Create Data Subsets
# =========================================================

In [61]:
# Select Specific Columns
subset_cols = df[['Type', 'like']]

In [62]:
# Display Selected Columns
display(subset_cols)

       Type    like
0     Photo    79.0
1    Status   130.0
2     Photo    66.0
3     Photo  1572.0
4     Photo   325.0
..      ...     ...
495   Photo    53.0
496   Photo    53.0
497   Photo    93.0
498   Photo    91.0
499   Photo    91.0

[500 rows x 2 columns]

In [63]:
# Select Rows Using Index
subset_rows = df.iloc[10:30]

In [64]:
# Display Selected Rows
display(subset_rows)

    Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  Lifetime Engaged Users  Lifetime Post Consumers  Lifetime Post Consumptions  Lifetime Post Impressions by people who have liked your Page  Lifetime Post reach by people who like your Page  Lifetime People who have liked your Page and engaged with your post  comment   like  share  Total Interactions
10            139441  Status         2          12             5         10   0.0                      21744                            42334                    4258                     4100                        4540                                              37849                                                        18952                                               3798                          0  233.0   19.0                 252
11            139441   Photo         2          12             5         10   0.0                       3112                             5590                     208                      127                         145                                               3887                                                         2174                                                165                          0   88.0   18.0                 106
12            139441   Photo         2          12             5         10   0.0                       2847                             5133                     193                      115                         133                                               3779                                                         2072                                                152                          0   90.0   14.0                 104
13            139441   Photo         2          12             5          3   0.0                       2549                             4896                     249                      134                         168                                               3631                                                         1917                                                183                          5  137.0   10.0                 152
14            138414   Photo         2          12             4          5   1.0                      22784                            39941                     887                      337                         417                                              34415                                                        19312                                                684                          2  577.0   20.0                 599
15            138414  Status         2          12             3         10   0.0                      10060                            19680                    1264                     1209                        1425                                              17272                                                         8548                                               1162                          4   86.0   18.0                 108
16            138414   Photo         3          12             3          3   0.0                       1722                             2981                     163                      123                         148                                               1868                                                         1050                                                123                          2   40.0   12.0                  54
17            138414   Photo         1          12             2         12   1.0                      53264                           111785                    1706                     1103                        1655                                              92512                                                        39776                                               1307                         15  678.0   20.0                 713
18            138414  Status         3          12             2          3   0.0                       3930                             7509                     130                       86                         112                                               5009                                                         2410                                                101                          4   54.0   17.0                  75
19            138414   Photo         3          12             1         11   0.0                       1591                             2825                     121                       88                         111                                               2116                                                         1161                                                100                          0   34.0    8.0                  42
20            138414   Photo         2          12             1          3   0.0                       2848                             5066                     200                      142                         184                                               3561                                                         1963                                                157                          3   66.0   12.0                  81
21            138414   Photo         1          12             7         10   0.0                       1384                             2467                      15                       15                          20                                               2196                                                         1172                                                 15                          0    0.0    0.0                   0
22            138414    Link         1          12             7         10   0.0                       3454                             6853                     118                      104                         130                                               6282                                                         3100                                                106                          0   16.0    2.0                  18
23            138414   Photo         3          12             7          3   0.0                       2723                             4888                     176                      118                         143                                               2964                                                         1621                                                143                          0   72.0   24.0                  96
24            138414  Status         2          12             6         10   0.0                       8488                            15294                    1341                     1270                        1489                                               9684                                                         5244                                                995                          3   99.0   19.0                 121
25            138458  Status         2          12             6          3   0.0                       8284                            15104                    1521                     1462                        1711                                              10266                                                         5372                                               1200                          0   88.0   18.0                 106
26            138458  Status         2          12             5         11   0.0                      19552                            34143                    2806                     2531                        3420                                              17748                                                         9824                                               1779                         10  412.0   72.0                 494
27            138458   Photo         3          12             5          3   0.0                       2478                             4306                     212                      124                         149                                               2612                                                         1443                                                166                          0  100.0   17.0                 117
28            138895   Photo         2          12             5          3   0.0                       9560                            18264                     973                      559                         885                                               9217                                                         4748                                                621                         36  523.0   63.0                 622
29            138895   Video         1          12             4         11   1.0                      36208                            61262                    1141                     1068                        1728                                              30131                                                        14112                                                559                         18  143.0   13.0                 174

In [65]:
# Conditional Subset
subset_cond = df[df['like'] > 100]

In [66]:
# Display Conditional Subset
display(subset_cond)

     Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  Lifetime Engaged Users  Lifetime Post Consumers  Lifetime Post Consumptions  Lifetime Post Impressions by people who have liked your Page  Lifetime Post reach by people who like your Page  Lifetime People who have liked your Page and engaged with your post  comment    like  share  Total Interactions
1              139441  Status         2          12             3         10   0.0                      10460                            19057                    1457                     1361                        1674                                              11710                                                         6112                                               1108                          5   130.0   29.0                 164
3              139441   Photo         2          12             2         10   1.0                      50128                            87991                    2211                      790                        1119                                              61027                                                        32048                                               1386                         58  1572.0  147.0                1777
4              139441   Photo         2          12             2          3   0.0                       7244                            13594                     671                      410                         580                                               6228                                                         3200                                                396                         19   325.0   49.0                 393
5              139441  Status         2          12             1          9   0.0                      10472                            20849                    1191                     1073                        1389                                              16034                                                         7852                                               1016                          1   152.0   33.0                 186
6              139441   Photo         3          12             1          3   1.0                      11692                            19479                     481                      265                         364                                              15432                                                         9328                                                379                          3   249.0   27.0                 279
..                ...     ...       ...         ...           ...        ...   ...                        ...                              ...                     ...                      ...                         ...                                                ...                                                          ...                                                ...                        ...     ...    ...                 ...
488             85979   Photo         3           1             7         10   0.0                       9700                            17442                    1407                     1271                        2007                                               8872                                                         4876                                                660                         21   277.0   80.0                 378
491             85979   Photo         3           1             6          3   1.0                       6184                            10228                     956                      901                        1140                                               6085                                                         3502                                                437                          1   105.0   46.0                 152
492             85979    Link         1           1             5         11   0.0                      45920                             5808                     753                      655                         763                                              15766                                                        10720                                                220                          0   128.0    9.0                 137
493             85093   Photo         3           1             1          2   0.0                       8412                            13960                    1179                     1111                        1632                                               8632                                                         5348                                                699                         17   185.0   55.0                 257
494             85093   Photo         3           1             7         10   0.0                       5400                             9218                     810                      756                        1003                                               5654                                                         3230                                                422                         10   125.0   41.0                 176

[252 rows x 19 columns]

In [67]:
# =========================================================
# b. Merge Data
# =========================================================

In [68]:
# Create Sample Subsets
df1 = df.iloc[0:20]
df2 = df.iloc[20:40]

In [69]:
# Merge Data
merged_df = pd.concat([df1, df2])

In [70]:
# Display Merged Data
display(merged_df)

    Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  Lifetime Engaged Users  Lifetime Post Consumers  Lifetime Post Consumptions  Lifetime Post Impressions by people who have liked your Page  Lifetime Post reach by people who like your Page  Lifetime People who have liked your Page and engaged with your post  comment    like  share  Total Interactions
0             139441   Photo         2          12             4          3   0.0                       2752                             5091                     178                      109                         159                                               3078                                                         1640                                                119                          4    79.0   17.0                 100
1             139441  Status         2          12             3         10   0.0                      10460                            19057                    1457                     1361                        1674                                              11710                                                         6112                                               1108                          5   130.0   29.0                 164
2             139441   Photo         3          12             3          3   0.0                       2413                             4373                     177                      113                         154                                               2812                                                         1503                                                132                          0    66.0   14.0                  80
3             139441   Photo         2          12             2         10   1.0                      50128                            87991                    2211                      790                        1119                                              61027                                                        32048                                               1386                         58  1572.0  147.0                1777
4             139441   Photo         2          12             2          3   0.0                       7244                            13594                     671                      410                         580                                               6228                                                         3200                                                396                         19   325.0   49.0                 393
5             139441  Status         2          12             1          9   0.0                      10472                            20849                    1191                     1073                        1389                                              16034                                                         7852                                               1016                          1   152.0   33.0                 186
6             139441   Photo         3          12             1          3   1.0                      11692                            19479                     481                      265                         364                                              15432                                                         9328                                                379                          3   249.0   27.0                 279
7             139441   Photo         3          12             7          9   1.0                      13720                            24137                     537                      232                         305                                              19728                                                        11056                                                422                          0   325.0   14.0                 339
8             139441  Status         2          12             7          3   0.0                      11844                            22538                    1530                     1407                        1692                                              15220                                                         7912                                               1250                          0   161.0   31.0                 192
9             139441   Photo         3          12             6         10   0.0                       4694                             8668                     280                      183                         250                                               4309                                                         2324                                                199                          3   113.0   26.0                 142
10            139441  Status         2          12             5         10   0.0                      21744                            42334                    4258                     4100                        4540                                              37849                                                        18952                                               3798                          0   233.0   19.0                 252
11            139441   Photo         2          12             5         10   0.0                       3112                             5590                     208                      127                         145                                               3887                                                         2174                                                165                          0    88.0   18.0                 106
12            139441   Photo         2          12             5         10   0.0                       2847                             5133                     193                      115                         133                                               3779                                                         2072                                                152                          0    90.0   14.0                 104
13            139441   Photo         2          12             5          3   0.0                       2549                             4896                     249                      134                         168                                               3631                                                         1917                                                183                          5   137.0   10.0                 152
14            138414   Photo         2          12             4          5   1.0                      22784                            39941                     887                      337                         417                                              34415                                                        19312                                                684                          2   577.0   20.0                 599
15            138414  Status         2          12             3         10   0.0                      10060                            19680                    1264                     1209                        1425                                              17272                                                         8548                                               1162                          4    86.0   18.0                 108
16            138414   Photo         3          12             3          3   0.0                       1722                             2981                     163                      123                         148                                               1868                                                         1050                                                123                          2    40.0   12.0                  54
17            138414   Photo         1          12             2         12   1.0                      53264                           111785                    1706                     1103                        1655                                              92512                                                        39776                                               1307                         15   678.0   20.0                 713
18            138414  Status         3          12             2          3   0.0                       3930                             7509                     130                       86                         112                                               5009                                                         2410                                                101                          4    54.0   17.0                  75
19            138414   Photo         3          12             1         11   0.0                       1591                             2825                     121                       88                         111                                               2116                                                         1161                                                100                          0    34.0    8.0                  42
20            138414   Photo         2          12             1          3   0.0                       2848                             5066                     200                      142                         184                                               3561                                                         1963                                                157                          3    66.0   12.0                  81
21            138414   Photo         1          12             7         10   0.0                       1384                             2467                      15                       15                          20                                               2196                                                         1172                                                 15                          0     0.0    0.0                   0
22            138414    Link         1          12             7         10   0.0                       3454                             6853                     118                      104                         130                                               6282                                                         3100                                                106                          0    16.0    2.0                  18
23            138414   Photo         3          12             7          3   0.0                       2723                             4888                     176                      118                         143                                               2964                                                         1621                                                143                          0    72.0   24.0                  96
24            138414  Status         2          12             6         10   0.0                       8488                            15294                    1341                     1270                        1489                                               9684                                                         5244                                                995                          3    99.0   19.0                 121
25            138458  Status         2          12             6          3   0.0                       8284                            15104                    1521                     1462                        1711                                              10266                                                         5372                                               1200                          0    88.0   18.0                 106
26            138458  Status         2          12             5         11   0.0                      19552                            34143                    2806                     2531                        3420                                              17748                                                         9824                                               1779                         10   412.0   72.0                 494
27            138458   Photo         3          12             5          3   0.0                       2478                             4306                     212                      124                         149                                               2612                                                         1443                                                166                          0   100.0   17.0                 117
28            138895   Photo         2          12             5          3   0.0                       9560                            18264                     973                      559                         885                                               9217                                                         4748                                                621                         36   523.0   63.0                 622
29            138895   Video         1          12             4         11   1.0                      36208                            61262                    1141                     1068                        1728                                              30131                                                        14112                                                559                         18   143.0   13.0                 174
30            138895   Photo         2          12             4          2   0.0                       4940                             9390                     385                      306                         501                                               5860                                                         2930                                                273                         33   107.0   22.0                 162
31            138895   Photo         2          12             3         10   0.0                       1683                             2929                     192                      171                         221                                               1585                                                          858                                                131                          1    27.0   11.0                  39
32            138895   Photo         3          12             3          3   0.0                       5280                             9578                     368                      237                         345                                               4480                                                         2422                                                268                          2   155.0   47.0                 204
33            138895   Photo         3          12             2          9   0.0                       3002                             5318                     268                      185                         247                                               3039                                                         1676                                                194                          4    98.0   23.0                 125
34            138895   Photo         1          12             2          3   0.0                       3766                             7149                     298                      260                         431                                               5782                                                         2938                                                244                          2    56.0   17.0                  75
35            138895   Photo         2          12             1         11   0.0                       4512                             7808                     423                      284                         431                                               5183                                                         2954                                                316                          6   172.0   21.0                 199
36            138895   Photo         3          12             1          3   0.0                       2690                             4628                     252                      168                         226                                               3052                                                         1727                                                199                          0    96.0   17.0                 113
37            138895   Photo         1          12             7         10   1.0                      19800                            28663                     479                      424                         805                                               5187                                                         2752                                                248                         16    76.0    8.0                 100
38            138895  Status         2          12             7          9   0.0                      17576                            33058                    5352                     5202                        6547                                              23135                                                        11792                                               4104                         11   227.0   31.0                 269
39            138895   Photo         1          12             7          3   0.0                       3290                             6085                     306                      284                         402                                               4986                                                         2584                                                247                          1    44.0   14.0                  59

In [71]:
# =========================================================
# c. Sort Data
# =========================================================

In [72]:
# Sort Data by Likes in Descending Order
sorted_df = df.sort_values(by='like', ascending=False)

In [73]:
# Display Sorted Data
display(sorted_df.head(20))

     Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  Lifetime Engaged Users  Lifetime Post Consumers  Lifetime Post Consumptions  Lifetime Post Impressions by people who have liked your Page  Lifetime Post reach by people who like your Page  Lifetime People who have liked your Page and engaged with your post  comment    like  share  Total Interactions
244            130791   Photo         2           7             3          5   1.0                     180480                           319133                    8072                     4010                        6242                                             108752                                                        51456                                               3316                        372  5172.0  790.0                6334
379            111620   Photo         3           4             1         14   1.0                     105632                           147918                    3984                     2254                        3391                                              48575                                                        27328                                               1936                         51  1998.0  128.0                2177
349            117764   Photo         3           5             5         13   0.0                      81856                           124753                    3000                     1637                        2718                                              52477                                                        27392                                               1756                         45  1639.0  122.0                1806
168            135428   Photo         1           9             3         10   0.0                      41984                            68290                    3370                     2420                        4074                                              34802                                                        20928                                               2126                        144  1622.0  208.0                1974
3              139441   Photo         2          12             2         10   1.0                      50128                            87991                    2211                      790                        1119                                              61027                                                        32048                                               1386                         58  1572.0  147.0                1777
460             92507   Photo         3           2             1         13   0.0                      55520                           665792                    4544                     3586                        6624                                             648611                                                        47488                                               3430                        146  1546.0  181.0                1873
101            137020   Photo         2          10             4          3   0.0                      68896                           104952                    2624                     1326                        1952                                              35707                                                        19840                                               1354                         26  1505.0   95.0                1626
323            123047   Photo         3           6             1         10   0.0                      56672                           104966                    2579                     1334                        1850                                              78678                                                        37408                                               1831                         20  1372.0   47.0                1439
199            132817   Photo         3           8             4         10   0.0                      33536                            64850                    1954                     1016                        1678                                              50076                                                        24448                                               1564                         33  1155.0  102.0                1290
176            135195   Photo         3           9             6          3   1.0                      22304                            37159                    1805                      984                        1618                                              22864                                                        13304                                               1349                         29  1047.0   98.0                1174
105            137020   Photo         1          10             2          4   0.0                      70144                           111745                    3216                     2628                        4782                                              43671                                                        20608                                               1542                         42   955.0  139.0                1136
142            136013  Status         2          10             3          2   1.0                      31136                            59964                    6164                     5934                        9237                                              35977                                                        18048                                               4376                         60   859.0   90.0                1009
206            132201   Photo         1           8             1          3   0.0                      50640                           121234                    2240                     1577                        2779                                              92348                                                        34880                                               1790                          4   859.0   68.0                 931
346            117764   Photo         3           5             7          2   0.0                      38960                            65149                    2298                     1702                        3000                                              57722                                                        34368                                               1978                         37   821.0   90.0                 948
191            133679   Photo         3           8             1         10   0.0                      19648                            33643                    1359                      695                         990                                              24034                                                        13528                                               1020                          9   766.0   43.0                 818
391            109670   Photo         2           4             1         13   1.0                      32208                            55696                    1933                     1367                        2123                                              43980                                                        24720                                               1568                          6   766.0  109.0                 881
254            129600   Photo         3           7             5          3   0.0                      54256                            82011                    1620                      963                        1419                                              42128                                                        24224                                                977                         10   755.0   58.0                 823
67             138185   Photo         1          11             7          3   1.0                      53456                            93790                    1576                      995                        1469                                              32646                                                        14912                                                884                         20   697.0   70.0                 787
270            128032   Photo         2           7             4          5   1.0                      53056                            65260                    2003                     1412                        2089                                              23679                                                        17104                                                975                          6   696.0   28.0                 730
17             138414   Photo         1          12             2         12   1.0                      53264                           111785                    1706                     1103                        1655                                              92512                                                        39776                                               1307                         15   678.0   20.0                 713

In [74]:
# =========================================================
# d. Transposing Data
# =========================================================

In [75]:
# Transpose Dataset
transposed_df = df.head().T

In [76]:
# Display Transposed Data
display(transposed_df)

                                                         0       1       2       3       4
Page total likes                                    139441  139441  139441  139441  139441
Type                                                 Photo  Status   Photo   Photo   Photo
Category                                                 2       2       3       2       2
Post Month                                              12      12      12      12      12
Post Weekday                                             4       3       3       2       2
Post Hour                                                3      10       3      10       3
Paid                                                   0.0     0.0     0.0     1.0     0.0
Lifetime Post Total Reach                             2752   10460    2413   50128    7244
Lifetime Post Total Impressions                       5091   19057    4373   87991   13594
Lifetime Engaged Users                                 178    1457     177    2211     671
Lifetime Post Consumers                                109    1361     113     790     410
Lifetime Post Consumptions                             159    1674     154    1119     580
Lifetime Post Impressions by people who have li...    3078   11710    2812   61027    6228
Lifetime Post reach by people who like your Page      1640    6112    1503   32048    3200
Lifetime People who have liked your Page and en...     119    1108     132    1386     396
comment                                                  4       5       0      58      19
like                                                  79.0   130.0    66.0  1572.0   325.0
share                                                 17.0    29.0    14.0   147.0    49.0
Total Interactions                                     100     164      80    1777     393

In [77]:
# =========================================================
# e. Shape and Reshape Data
# =========================================================

In [78]:
# Display Shape
print("Shape of Dataset:", df.shape)


# Convert Numeric Data into NumPy Array
arr = df.select_dtypes(include=np.number).to_numpy()

# Display Array
print(arr)

Shape of Dataset: (500, 19)
[[1.39441e+05 2.00000e+00 1.20000e+01 ... 7.90000e+01 1.70000e+01
  1.00000e+02]
 [1.39441e+05 2.00000e+00 1.20000e+01 ... 1.30000e+02 2.90000e+01
  1.64000e+02]
 [1.39441e+05 3.00000e+00 1.20000e+01 ... 6.60000e+01 1.40000e+01
  8.00000e+01]
 ...
 [8.13700e+04 1.00000e+00 1.00000e+00 ... 9.30000e+01 1.80000e+01
  1.15000e+02]
 [8.13700e+04 3.00000e+00 1.00000e+00 ... 9.10000e+01 3.80000e+01
  1.36000e+02]
 [8.13700e+04 2.00000e+00 1.00000e+00 ... 9.10000e+01 2.80000e+01
  1.19000e+02]]

In [79]:
# Reshape Array into Single Dimension
reshaped_arr = arr.reshape(-1)

# Display Reshaped Array
print(reshaped_arr)

[1.39441e+05 2.00000e+00 1.20000e+01 ... 9.10000e+01 2.80000e+01
 1.19000e+02]

In [80]:
# Reshape Array into 2 Columns
reshaped_arr = arr.reshape(-1, 2)

# Display Reshaped Array
print(reshaped_arr)

1. # -1 Python automatically calculates number of rows.

2. # 2 Creates exactly 2 columns.

[[1.39441e+05 2.00000e+00]
 [1.20000e+01 4.00000e+00]
 [3.00000e+00 0.00000e+00]
 ...
 [2.20000e+03 3.16000e+02]
 [0.00000e+00 9.10000e+01]
 [2.80000e+01 1.19000e+02]]

2.0

In [81]:
# Check Total Elements
print(arr.size)

# Reshape into 2 Columns
reshaped_arr = arr.reshape(-1, 2)

# Display Reshaped Array
print(reshaped_arr)

9000
[[1.39441e+05 2.00000e+00]
 [1.20000e+01 4.00000e+00]
 [3.00000e+00 0.00000e+00]
 ...
 [2.20000e+03 3.16000e+02]
 [0.00000e+00 9.10000e+01]
 [2.80000e+01 1.19000e+02]]

In [82]:
# =========================================================
# COMPLETE VIVA + MODIFICATION NOTES
# FACEBOOK METRICS DATASET PRACTICAL
# =========================================================


# =========================================================
# 1. WHAT IS THIS PRACTICAL?
# =========================================================

# This practical performs Data Manipulation Operations
# using Pandas on Facebook Metrics Dataset.

# Operations Performed:
# a. Create Data Subsets
# b. Merge Data
# c. Sort Data
# d. Transpose Data
# e. Shape and Reshape Data


# =========================================================
# 2. IMPORTANT LIBRARIES
# =========================================================

# import pandas as pd
# Used for DataFrame operations.

# import numpy as np
# Used for array and numerical operations.


# =========================================================
# 3. WHY sep=';' IS USED?
# =========================================================

# Facebook dataset columns are separated using semicolon (;)
# instead of comma (,)

# Example:
# df = pd.read_csv("dataset_Facebook.csv", sep=';')


# =========================================================
# 4. WHY pd.set_option() IS USED?
# =========================================================

# Used to display large datasets properly.

# pd.set_option('display.max_columns', None)
# Shows all columns.

# pd.set_option('display.width', 3000)
# Increases display width.


# =========================================================
# 5. WHAT IS A DATAFRAME?
# =========================================================

# A DataFrame is a 2-dimensional tabular structure
# containing rows and columns.


# =========================================================
# 6. WHAT IS A SUBSET?
# =========================================================

# A subset is a smaller portion of dataset selected
# from rows or columns.


# =========================================================
# 7. COLUMN SUBSET
# =========================================================

# subset_cols = df[['Type', 'like']]

# Meaning:
# Select only Type and like columns.

# If external asks:
# "Select 3 columns"

# Example:
# subset_cols = df[['Type', 'like', 'share']]


# =========================================================
# 8. ROW SUBSET USING iloc
# =========================================================

# subset_rows = df.iloc[10:30]

# Meaning:
# Select rows from index 10 to 29.

# iloc = Integer Location

# If external asks:
# "Take first 5 rows"

# Example:
# df.iloc[0:5]

# If external asks:
# "Take rows 50 to 100"

# Example:
# df.iloc[50:100]


# =========================================================
# 9. CONDITIONAL SUBSET
# =========================================================

# subset_cond = df[df['like'] > 100]

# Meaning:
# Select rows where likes are greater than 100.

# If external asks:
# "Show likes greater than 500"

# Example:
# df[df['like'] > 500]

# If external asks:
# "Filter by comments"

# Example:
# df[df['comment'] > 20]

# If external asks:
# "Use AND condition"

# Example:
# df[(df['like'] > 100) & (df['share'] > 20)]

# If external asks:
# "Use OR condition"

# Example:
# df[(df['like'] > 100) | (df['share'] > 20)]


# =========================================================
# 10. WHAT IS CONCAT / MERGE?
# =========================================================

# pd.concat() combines datasets together.

# Example:
# merged_df = pd.concat([df1, df2])

# If external asks:
# "Merge 3 subsets"

# Example:
# merged_df = pd.concat([df1, df2, df3])


# =========================================================
# 11. WHAT IS SORTING?
# =========================================================

# Sorting arranges data in ascending or descending order.

# Example:
# df.sort_values(by='like')

# Ascending:
# ascending=True

# Descending:
# ascending=False


# =========================================================
# 12. IF EXTERNAL ASKS:
# "Sort by comments"
# =========================================================

# df.sort_values(by='comment', ascending=False)


# =========================================================
# 13. IF EXTERNAL ASKS:
# "Sort by multiple columns"
# =========================================================

# df.sort_values(by=['like', 'share'], ascending=False)


# =========================================================
# 14. WHAT IS TRANSPOSE?
# =========================================================

# Transpose converts:
# rows -> columns
# columns -> rows

# Example:
# df.T

# If external asks:
# "Transpose first 5 rows"

# Example:
# df.head().T


# =========================================================
# 15. WHAT IS SHAPE?
# =========================================================

# df.shape

# Returns:
# (rows, columns)

# Example:
# (500, 19)


# =========================================================
# 16. WHAT IS NUMPY ARRAY?
# =========================================================

# arr = df.to_numpy()

# Converts DataFrame into NumPy array.


# =========================================================
# 17. WHY select_dtypes() IS USED?
# =========================================================

# Used to select only numeric columns.

# Example:
# arr = df.select_dtypes(include=np.number).to_numpy()

# Reason:
# reshape works properly with numeric values.


# =========================================================
# 18. WHAT IS RESHAPE?
# =========================================================

# reshape changes dimensions of array.

# Example:
# arr.reshape(-1)

# Converts into 1D array.


# =========================================================
# 19. reshape(-1,2)
# =========================================================

# Meaning:
# Create 2 columns.
# Python automatically calculates rows.


# =========================================================
# 20. IF EXTERNAL ASKS:
# "Reshape into 3 columns"
# =========================================================

# reshaped_arr = arr.reshape(-1,3)


# =========================================================
# 21. COMMON ERROR
# =========================================================

# ValueError: cannot reshape array

# Reason:
# Total elements not divisible properly.


# =========================================================
# 22. WHAT IS display()?
# =========================================================

# display(df)

# Shows structured table output in Jupyter Notebook.


# =========================================================
# 23. WHY print(df) LOOKS UNSTRUCTURED?
# =========================================================

# print() converts DataFrame into plain text output.

# display() shows formatted HTML table.


# =========================================================
# 24. DIFFERENCE BETWEEN loc AND iloc
# =========================================================

# loc:
# Label-based selection.

# iloc:
# Index-based selection.


# =========================================================
# 25. IF EXTERNAL ASKS:
# "SHOW ONLY NUMERIC COLUMNS"
# =========================================================

# df.select_dtypes(include=np.number)


# =========================================================
# 26. IF EXTERNAL ASKS:
# "SHOW ONLY STRING COLUMNS"
# =========================================================

# df.select_dtypes(include='object')


# =========================================================
# 27. IF EXTERNAL ASKS:
# "DISPLAY COLUMN NAMES"
# =========================================================

# print(df.columns)


# =========================================================
# 28. IF EXTERNAL ASKS:
# "DISPLAY DATA TYPES"
# =========================================================

# print(df.dtypes)


# =========================================================
# 29. IF EXTERNAL ASKS:
# "DISPLAY LAST 5 ROWS"
# =========================================================

# df.tail()


# =========================================================
# 30. IF EXTERNAL ASKS:
# "DISPLAY RANDOM ROWS"
# =========================================================

# df.sample(5)


# =========================================================
# 31. IF EXTERNAL ASKS:
# "COUNT TOTAL NULL VALUES"
# =========================================================

# df.isnull().sum()


# =========================================================
# 32. IF EXTERNAL ASKS:
# "REMOVE NULL VALUES"
# =========================================================

# df.dropna(inplace=True)


# =========================================================
# 33. IF EXTERNAL ASKS:
# "REMOVE DUPLICATES"
# =========================================================

# df.drop_duplicates(inplace=True)


# =========================================================
# 34. IF EXTERNAL ASKS:
# "SAVE NEW DATASET"
# =========================================================

# df.to_csv("new_dataset.csv", index=False)


# =========================================================
# 35. IMPORTANT OUTPUT QUESTIONS
# =========================================================

# Why output wraps?
# Because dataset has many long column names.

# Why use display()?
# For proper tabular formatting.

# Why transpose output?
# Makes long columns easier to read.


# =========================================================
# 36. MOST IMPORTANT VIVA QUESTIONS
# =========================================================

# Q. What is Pandas?
# Pandas is a Python library for data analysis and manipulation.

# Q. What is NumPy?
# NumPy is a Python library for numerical and array operations.

# Q. What is Data Manipulation?
# Process of organizing, transforming, and modifying data.

# Q. What is sorting?
# Arranging data in ascending or descending order.

# Q. What is filtering?
# Selecting rows based on conditions.

# Q. What is merge?
# Combining multiple datasets.

# Q. What is transpose?
# Converting rows into columns and columns into rows.

# Q. What is reshape?
# Changing dimensions of data.

# Q. Why use Jupyter Notebook?
# Interactive execution and visualization of code.

# Q. Why use Facebook dataset?
# To analyze social media engagement metrics.


# =========================================================
# 37. MOST IMPORTANT COMMANDS
# =========================================================

# df.head()
# First 5 rows

# df.tail()
# Last 5 rows

# df.shape
# Shape of dataset

# df.columns
# Column names

# df.dtypes
# Data types

# df.describe()
# Statistical summary

# df.info()
# Dataset information


# =========================================================
# END OF COMPLETE VIVA NOTES
# =========================================================